### ISSUE TITLE
Add New Check Boxes in SettingsActivity

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#34]
## Following CheckBoxes Should Be included in Setting activity
- codeforces.com 
- codechef.com
- hackerearth.com 
- leetcode.com 
- topcoder.com
- atcoder.jp
- hackerrank.com 
- codingcompetitions.withgoogle.com spoj.com

### - Refactor Margins/Paddings : Every CardView Should Have **8dp** MarginTop, Remove Padding in ScrollView

**Comment by fenu28** [comment]
I want to work on this issue. Can you assign this to me?

**Comment by HemangNakarani** [comment]
@fenu28 Go ahed !! 👍

**Comment by fenu28** [comment]
@HemangNakarani I have a confusion in the validation part of checkboxes. What I have understood and changed in the code is, if the user deselects all the checkboxes, then the Codeforces checkbox gets turned on by default and a toast message is also displayed "Atlease 1 platform has to be selected". Am I doing this in a correct way ?

**Comment by HemangNakarani** [comment]
> @HemangNakarani I have a confusion in the validation part of checkboxes. What I have understood and changed in the code is, if the user deselects all the checkboxes, then the Codeforces checkbox gets turned on by default and a toast message is also displayed "Atlease 1 platform has to be selected". Am I doing this in a correct way ?

Yeah, you can do this, it's ok.

**Comment by fenu28** [comment]
@HemangNakarani Can you guide me in this issue because my solution is not dynamic. My solution still allows user to deselect all the options and the default Codeforces is set only when onBackPressed() is called. What I am trying to implement is, as soon as user deselects all options, the Codeforces checkbox is set. I will also not be able to pull a PR bcoz there is already one PR from someone modifying the onBackPressed () method.
